name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
    simple_deployment_pipeline:
        if: ${{ github.event_name == 'push' }}
        runs-on: ubuntu-20.04
        permissions: # Required if github_deployment is set to true.
          deployments: write
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
            with:
              node-version: '16'

          - name: Install dependencies
            run: npm install

          - name: lint
            run: npm run eslint

          - name: Check build
            run: npm run build

          - name: test
            run: npm run test

          - name: e2e tests
            uses: cypress-io/github-action@v5
            with:
              command: npm run test:e2e
              start: npm run start-prod
              wait-on: http://localhost:5000

          - name: deploy
            if: ${{ !contains(toJson(github.event.commits.*.message),'#skip') }}
            env:
                deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
            run: |
                echo "Deploying to $deploy_url"
                curl "$deploy_url"
          
    tag_release:
      if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message),'#skip') }}
      needs: [simple_deployment_pipeline]
      permissions:
        contents: write
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: '0'
        - name: Bump version and push tag
          uses: anothrNick/github-tag-action@1.64.0
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
            WITH_V: true
            DEFAULT_BUMP: patch