name: Deployment Pipeline

on:
  push:
    branches:
      - master

  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Check Style
        run: npm run eslint

      - name: Check Build
        run: npm run build

      - name: Check Tests
        run: npm run test

      - name: Run E2E Tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000

  deploy:
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest

    permissions:
      deployments: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Info
        run: |
          echo "GitHub Event Name: ${{ github.event_name }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "Commits: ${{ toJson(github.event.commits) }}"
          echo "Commit Messages: ${{ toJson(github.event.commits.*.message) }}"
          echo "Skip Check: ${{ contains(toJson(github.event.commits.*.message), '#skip') }}"
          echo "Running on Branch: ${{ github.ref == 'refs/heads/master' }}"
          
      - name: Deploy to Render
        # Only run this step if the branch is master
        if: github.ref == 'refs/heads/master'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          echo "Deploying to $deploy_url"
          curl "$deploy_url"
